using System;

namespace NHibernate.Annotations
{
	/// <summary>
	/// The annotated property is generated by the database
	/// </summary>
	public class GeneratedAttribute : Attribute
	{
		public GenerationTime? Value { get; set; }
	}
}