using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.Burrow")]
[assembly: AssemblyDescriptionAttribute("An light weight framework to support NHibernate based applications.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.Burrow")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("1.0.0.3002")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.3002")]
[assembly: AssemblyFileVersionAttribute("1.0.0.3002")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]

