using System;
using System.Reflection;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.UserTypes.SqlTypes")]
[assembly: AssemblyDescriptionAttribute("System.Data.SqlTypes support for NHibernate 2.0.0.Alpha1")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.UserTypes.SqlTypes")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("2.0.0.1001")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.1001")]
[assembly: AssemblyFileVersionAttribute("2.0.0.1001")]
//[assembly: AssemblyKeyFileAttribute("../../src/NHibernate.snk")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallers()]
