//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernate.NHDesigner
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "nhx";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"NHDesigner";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"NHibernate";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.1.0.1";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID NHDesignerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHDesignerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID NHDesignerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHDesignerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewNHDesignerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHDesignerCommandSetId), 0x0001);
	
		// Package identifier
		public const string NHDesignerPackageId = "7eccb11c-fa71-4885-b37d-7b522c76c608";
		
		// Editor factory identifier
		public const string NHDesignerEditorFactoryId = "7eb0a134-abf8-459b-8c0f-f697a08ef867";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string NHDesignerModelExplorerToolWindowId = "eba6ef16-e410-4b8c-928a-1be541ae7a62";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace NHibernate.NHDesigner
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string NHDesignerCommandSetId = "4f82f8fb-816f-4716-bac9-346bb96161d1";
	}
}