//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.4200
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
[System.Xml.Serialization.XmlRootAttribute("db2hbm-conf", Namespace="urn:nhibernate-codegen-2.2", IsNullable=false)]
public partial class db2hbmconf {
    
    private string[] metadatastrategiesField;
    
    private string namingstrategyField;
    
    private db2hbmconfConnectioninfo connectioninfoField;
    
    private db2hbmconfTable[] tablesField;
    
    private string entitiesnamespaceField;
    
    private string entitiesassemblyField;
    
    private object outputfolderField;
    
    private db2hbmconfProperty[] additionalpropertiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("metadata-strategies")]
    [System.Xml.Serialization.XmlArrayItemAttribute("strategy", IsNullable=false)]
    public string[] metadatastrategies {
        get {
            return this.metadatastrategiesField;
        }
        set {
            this.metadatastrategiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("naming-strategy")]
    public string namingstrategy {
        get {
            return this.namingstrategyField;
        }
        set {
            this.namingstrategyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connection-info")]
    public db2hbmconfConnectioninfo connectioninfo {
        get {
            return this.connectioninfoField;
        }
        set {
            this.connectioninfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable=false)]
    public db2hbmconfTable[] tables {
        get {
            return this.tablesField;
        }
        set {
            this.tablesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entities-namespace")]
    public string entitiesnamespace {
        get {
            return this.entitiesnamespaceField;
        }
        set {
            this.entitiesnamespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entities-assembly")]
    public string entitiesassembly {
        get {
            return this.entitiesassemblyField;
        }
        set {
            this.entitiesassemblyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("output-folder")]
    public object outputfolder {
        get {
            return this.outputfolderField;
        }
        set {
            this.outputfolderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("additional-properties")]
    [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
    public db2hbmconfProperty[] additionalproperties {
        get {
            return this.additionalpropertiesField;
        }
        set {
            this.additionalpropertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
public partial class db2hbmconfConnectioninfo {
    
    private string dialectField;
    
    private string connectionstringField;
    
    private string connectiondriverField;
    
    /// <remarks/>
    public string dialect {
        get {
            return this.dialectField;
        }
        set {
            this.dialectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connection-string")]
    public string connectionstring {
        get {
            return this.connectionstringField;
        }
        set {
            this.connectionstringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connection-driver")]
    public string connectiondriver {
        get {
            return this.connectiondriverField;
        }
        set {
            this.connectiondriverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
public partial class db2hbmconfTable {
    
    private string schemaField;
    
    private string catalogField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string schema {
        get {
            return this.schemaField;
        }
        set {
            this.schemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string catalog {
        get {
            return this.catalogField;
        }
        set {
            this.catalogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
public partial class db2hbmconfProperty {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
