//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace cfg {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    [System.Xml.Serialization.XmlRootAttribute("db2hbm-conf", Namespace="urn:nhibernate-codegen-2.2", IsNullable=false)]
    public partial class db2hbmconf {
        
        private classref[] metadatastrategiesField;
        
        private string[] foreignkeycrawlersField;
        
        private db2hbmconfSqltype[] typemappingField;
        
        private classref namingstrategyField;
        
        private db2hbmconfConnectioninfo connectioninfoField;
        
        private db2hbmconfTable[] tablesField;
        
        private string entitiesnamespaceField;
        
        private string entitiesassemblyField;
        
        private object outputfolderField;
        
        private db2hbmconfProperty[] additionalpropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("metadata-strategies")]
        [System.Xml.Serialization.XmlArrayItemAttribute("strategy", IsNullable=false)]
        public classref[] metadatastrategies {
            get {
                return this.metadatastrategiesField;
            }
            set {
                this.metadatastrategiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("foreign-key-crawlers")]
        [System.Xml.Serialization.XmlArrayItemAttribute("factory", IsNullable=false)]
        public string[] foreignkeycrawlers {
            get {
                return this.foreignkeycrawlersField;
            }
            set {
                this.foreignkeycrawlersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("type-mapping")]
        [System.Xml.Serialization.XmlArrayItemAttribute("sql-type", IsNullable=false)]
        public db2hbmconfSqltype[] typemapping {
            get {
                return this.typemappingField;
            }
            set {
                this.typemappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("naming-strategy")]
        public classref namingstrategy {
            get {
                return this.namingstrategyField;
            }
            set {
                this.namingstrategyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("connection-info")]
        public db2hbmconfConnectioninfo connectioninfo {
            get {
                return this.connectioninfoField;
            }
            set {
                this.connectioninfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable=false)]
        public db2hbmconfTable[] tables {
            get {
                return this.tablesField;
            }
            set {
                this.tablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entities-namespace")]
        public string entitiesnamespace {
            get {
                return this.entitiesnamespaceField;
            }
            set {
                this.entitiesnamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entities-assembly")]
        public string entitiesassembly {
            get {
                return this.entitiesassemblyField;
            }
            set {
                this.entitiesassemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("output-folder")]
        public object outputfolder {
            get {
                return this.outputfolderField;
            }
            set {
                this.outputfolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("additional-properties")]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public db2hbmconfProperty[] additionalproperties {
            get {
                return this.additionalpropertiesField;
            }
            set {
                this.additionalpropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="class-ref", Namespace="urn:nhibernate-codegen-2.2")]
    public partial class classref {
        
        private classrefProperty[] propertyField;
        
        private string classField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public classrefProperty[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class classrefProperty {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfSqltype {
        
        private string dbtypeField;
        
        private string nhtypeField;
        
        private int lengthField;
        
        private bool lengthFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dbtype {
            get {
                return this.dbtypeField;
            }
            set {
                this.dbtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nhtype {
            get {
                return this.nhtypeField;
            }
            set {
                this.nhtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfConnectioninfo {
        
        private string dialectField;
        
        private string connectionstringField;
        
        private string connectiondriverField;
        
        /// <remarks/>
        public string dialect {
            get {
                return this.dialectField;
            }
            set {
                this.dialectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("connection-string")]
        public string connectionstring {
            get {
                return this.connectionstringField;
            }
            set {
                this.connectionstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("connection-driver")]
        public string connectiondriver {
            get {
                return this.connectiondriverField;
            }
            set {
                this.connectiondriverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfTable {
        
        private db2hbmconfTablePrimarykey primarykeyField;
        
        private db2hbmconfTableForeignkey[] foreignkeyField;
        
        private string schemaField;
        
        private string catalogField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("primary-key")]
        public db2hbmconfTablePrimarykey primarykey {
            get {
                return this.primarykeyField;
            }
            set {
                this.primarykeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("foreign-key")]
        public db2hbmconfTableForeignkey[] foreignkey {
            get {
                return this.foreignkeyField;
            }
            set {
                this.foreignkeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfTablePrimarykey {
        
        private db2hbmconfTablePrimarykeyGenerator generatorField;
        
        private db2hbmconfTablePrimarykeyKeycolumn[] keycolumnField;
        
        /// <remarks/>
        public db2hbmconfTablePrimarykeyGenerator generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("key-column")]
        public db2hbmconfTablePrimarykeyKeycolumn[] keycolumn {
            get {
                return this.keycolumnField;
            }
            set {
                this.keycolumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfTablePrimarykeyGenerator {
        
        private db2hbmconfTablePrimarykeyGeneratorParam[] paramField;
        
        private string classField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("param")]
        public db2hbmconfTablePrimarykeyGeneratorParam[] param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfTablePrimarykeyGeneratorParam {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfTablePrimarykeyKeycolumn {
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfTableForeignkey {
        
        private db2hbmconfTableForeignkeyColumnref[] columnrefField;
        
        private string constraintnameField;
        
        private string foreigncatalogField;
        
        private string foreignschemaField;
        
        private string foreigntableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("column-ref")]
        public db2hbmconfTableForeignkeyColumnref[] columnref {
            get {
                return this.columnrefField;
            }
            set {
                this.columnrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("constraint-name")]
        public string constraintname {
            get {
                return this.constraintnameField;
            }
            set {
                this.constraintnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-catalog")]
        public string foreigncatalog {
            get {
                return this.foreigncatalogField;
            }
            set {
                this.foreigncatalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-schema")]
        public string foreignschema {
            get {
                return this.foreignschemaField;
            }
            set {
                this.foreignschemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-table")]
        public string foreigntable {
            get {
                return this.foreigntableField;
            }
            set {
                this.foreigntableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfTableForeignkeyColumnref {
        
        private string localcolumnField;
        
        private string foreigncolumnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("local-column")]
        public string localcolumn {
            get {
                return this.localcolumnField;
            }
            set {
                this.localcolumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-column")]
        public string foreigncolumn {
            get {
                return this.foreigncolumnField;
            }
            set {
                this.foreigncolumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nhibernate-codegen-2.2")]
    public partial class db2hbmconfProperty {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
