using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("NHibernate.Burrow.Test")]
[assembly: AssemblyDescriptionAttribute("The Unit Tests for NHibernate.Burrow.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.Burrow.Test")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("1.0.0.1004")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.1004")]
[assembly: AssemblyFileVersionAttribute("1.0.0.1004")]
[assembly: AssemblyDelaySignAttribute(false)]

