using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.UserTypes.SqlTypes.Tests")]
[assembly: AssemblyDescriptionAttribute("Tests for NHibernate.UserTypes.SqlTypes group of assemblies")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.UserTypes.SqlTypes.Tests")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("2.0.0.1001")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.1001")]
[assembly: AssemblyFileVersionAttribute("2.0.0.1001")]
[assembly: AssemblyDelaySignAttribute(false)]

